name: Deploy RPS Simulator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.RPS_SIMULATOR_HOST }}
          username: ${{ secrets.RPS_SIMULATOR_USERNAME }}
          key: ${{ secrets.RPS_SIMULATOR_SSH_KEY }}
          script: |
            cd /home/${{ secrets.RPS_SIMULATOR_USERNAME }}/rps-simulator

            git pull origin main

            docker compose down
            docker compose up -d --build